config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/contact' => 'site#contact'
  root to: 'site#home'
  resources :projects do
    resources :entries
  end

  namespace :api do
    resources :projects, only: [:show, :index, :create]
  end

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	
	belongs_to :project

	validates :hours, :minutes, numericality: true, presence: true
	validates :date, presence: true
	validates :project_id, presence: true

	validate :project_exists

	def project_exists
		unless Project.find_by(id: project_id)
			errors.add(:project_id, 'does not exist')
		end
	end
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :memberships
	has_many :projects
end

app/models/membership.rb
class Membership < ActiveRecord::Base

	belongs_to :user
	belongs_to :group
end

app/models/project.rb
class Project < ActiveRecord::Base
	# def self.iron_find (id)
	# 	where(id: id).first
		# end

	belongs_to :group
	has_many :entries

	validates :name, presence: true
	validates :name, uniqueness: true
	validates :name, length: {maximum:30}
	validates :name, format: {with: /\A[\w\s*]+\Z/}


	def self.last_created_projects (number)
		order(created_at: :desc).limit(number)
	end

	def total_hours
		hours = 0
		minutes = 0
		entries.each do |entry|
			hours += entry.hours
			minutes += entry.minutes
		end
		hours + (minutes / 60)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :memberships
  has_many :groups, through: :memberships
  has_many :projects, through: :groups

end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
	def index
		@projects = Project.all.includes(:entries)
	end

	def create
		@project = Project.create(project_params)
	end

	private

	def project_params
		params.require(:project).permit(:name)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

	before_action :authenticate_user!

	def index
		@project = current_user.projects.find_by id: params[:project_id]
		@entries = @project.entries
	end

	def new
		@project = current_user.projects.find params[:project_id]
		@entry = @project.entries.new
	end

	def create
		@project = current_user.projects.find params[:project_id]
		@entry = @project.entries.new entry_params

		if @entry.save
			flash[:notice] = "Entry created succesfully"
			UserMailer.entry_created(@project).deliver
			redirect_to action: 'index', controller: 'entries', project_id: @project.id
		else
			render 'new'
		end
	end

	def edit
		@project = current_user.projects.find params[:project_id]
		@entry = @project.entries.find params[:id]
	end

	def update
		@project = current_user.projects.find params[:project_id]
		@entry = project.entries.find params[:id]

		if @entry.update_atribbutes entry_params
			redirect_to action: :show, controller: :entries, project_id: @project_id, id: @entry.id
		else
			render 'edit'
		end
	end

	def show
		@project = current_user.projects.find_by id: params[:project_id]
		@entries = @project.entries
	end

	def destroy
		@project = current_user.projects.find_by id: params[:project_id]
		@entry = @project.entries.find params[:id]

		if @entry.destroy
			redirect_to action: :index
		else
			redirect_to :back
		end
	end


	private

	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :authenticate_user!
    def index
        @projects = current_user.projects.last_created_projects(10)
        render 'no_projects' if @projects.empty?
    end
    def show
        @project = current_user.projects.find_by id: params[:id]
        render 'no_project_found' unless @project
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
		# render 'home'
	end

	def contact
		# render 'contact' - no hace falta ponerlo pq por defecto coge la ruta del nombre de la acción
	end
end

app/helpers/api/projects_helper.rb
module Api::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

def flash_message
    flash.key.map do |type|
      message_div(type)
    end.join.html_safe
  end


  private

  def message_div(type)
    content_tag :div, class: 'message ' + type.to_s do
      content_tag :p do
        message
      end
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/entries/edit.html.erb

	<div class="row">
		<div class="col-md-4"></div>
	  	<div class="col-md-4">
			<%= form_for [@project, @entry] do |f| %>
				<%= f.label :hours %>
				<%= f.text_field :hours, size: 4, class: "form-control" %>
				</br>
				<%= f.label :minutes %>
				<%= f.text_field :minutes, size: 4, class: "form-control" %>
				</br>
				<%= f.label :date  %>
				<%= f.date_select :date, size: 4, class: "form-control input-lg" %>
				</br>

				<%= f.submit class: "btn btn-primary btn-sm" %>
				<%= link_to('Cancel', project_entries_path(@project), class: "btn btn-default btn-sm")  %>
			<% end %>
		</div>
		<div class="col-md-4"></div>
	</div>


app/views/entries/index.html.erb
<div class "row mtop">
  	<div class="col-md-4 col-md-offset-4 bgray" style="padding: 30px">
		<% if flash[:notice] %>
			<%= flash[:notice] %>
		<% end %>

		<h1><%= @project.name %></h1>
		<ul>
		 <% @entries.each do |entry| %>
		   <li>
		       <%= entry.hours %> h
		       <%= entry.minutes %> m -
		       <%= entry.date %>
		       <%= link_to('Edit', edit_project_entry_path(@project, entry)) %>

		       <%= link_to('Delete', project_entry_path(@project, entry), method: :delete, data: {confirm: "Are your sure?"}) %>
		   </li>
		 <% end %>
		</ul>
		<%= link_to('Index', projects_path(), class: "btn btn-default btn-sm") %>
		<%= link_to('New entry', new_project_entry_path(),  class: "btn btn-success btn-sm") %>
	</div>
</div>

app/views/entries/new.html.erb
<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<div class="row">
  	<div class="col-md-4 col-md-offset-4 bgray" style="padding: 30px">
		<%= form_for [@project, @entry] do |f| %>
			<%= f.label :hours %>
			<%= f.text_field :hours, class: "form-control" %>
			</br>
			<%= f.label :minutes %>
			<%= f.text_field :minutes, class: "form-control" %>
			</br>
			<%= f.label :date  %>
			<%= f.date_select :date, {}, {:class => "form-control mtop"} %>
			</br>

			<%= f.submit class: "btn btn-primary btn-sm" %>
			<%= link_to('Cancel', project_entries_path(@project), class: "btn btn-default btn-sm")  %>
		<% end %>
	</div>
</div>

app/views/entries/show.html.erb
<h1><%= @project.name %></h1>
<ul>
 <% @entries.each do |entry| %>
   <li>
       <%= entry.hours %> h
       <%= entry.minutes %> m -
       <%= entry.date %>
   </li>
 <% end %>
</ul>
<%= link_to('Index', projects_path()) %>
<%= link_to('New entry', new_project_entry_path()) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Timetraking</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
	</head>

	<body>

		<%= yield %>

	</body>
</html>

app/views/projects/index.html.erb
<ul>
	<% @projects.each do |project| %>
	<li> <%= link_to(project.name, project_entries_path(project)) %>
		<% if project.description.present? %>
		- <%= project.description %>
		<% end %>
	</li>
	<% end %>
</ul>


app/views/projects/no_projects.html.erb
<h1>
	No projects found
</h1>	

app/views/projects/project_not_found.html.erb
<h1>
	Project not found with id: <%= params [:id] %>
</h1>	

app/views/projects/show.html.erb
<h1>
	<%= @project.name %>
</h1>

<p>
	<%= @project.description %>
</p>

app/views/site/contact.html.erb
<p>example@contact.com</p>

app/views/site/home.html.erb
<h1>Welcome to this timetracking tool</h1>
<p>Ironhack powered</p>